--Script de ejecucion de base de datos (¡¡IMPORTANTE!! ir ejecutando por bloques )


--crear base de datos, también se puede con click derecho en el dbeaver
CREATE DATABASE IF NOT EXISTS matchup;


--insertar categorias
INSERT INTO categoria (nombre) VALUES
('Deporte'),
('Senderismo'),
('Conciertos'),
('Cine'),
('Música'),
('Viajar'),
('Bienestar'),
('Juegos'),
('Gastronomía'),
('Yoga'),
('Arte'),
('Museo'),
('Fotografía'),
('Idiomas'),
('Baile'),
('Cantar'),
('Videojuegos'),
('Naturaleza'),
('Animales'),
('Lectura'),
('Tecnología'),
('Salir'),
('Moda');



--insertar paises
INSERT INTO pais (nombre) VALUES
('Afganistán'),
('Albania'),
('Alemania'),
('Andorra'),
('Angola'),
('Antigua y Barbuda'),
('Arabia Saudita'),
('Argelia'),
('Argentina'),
('Armenia'),
('Australia'),
('Austria'),
('Azerbaiyán'),
('Bahamas'),
('Bangladés'),
('Barbados'),
('Baréin'),
('Bélgica'),
('Belice'),
('Benín'),
('Bielorrusia'),
('Birmania'),
('Bolivia'),
('Bosnia y Herzegovina'),
('Botsuana'),
('Brasil'),
('Brunéi'),
('Bulgaria'),
('Burkina Faso'),
('Burundi'),
('Bután'),
('Cabo Verde'),
('Camboya'),
('Camerún'),
('Canadá'),
('Catar'),
('Chad'),
('Chile'),
('China'),
('Chipre'),
('Colombia'),
('Comoras'),
('Corea del Norte'),
('Corea del Sur'),
('Costa de Marfil'),
('Costa Rica'),
('Croacia'),
('Cuba'),
('Dinamarca'),
('Dominica'),
('Ecuador'),
('Egipto'),
('El Salvador'),
('Emiratos Árabes Unidos'),
('Eritrea'),
('Eslovaquia'),
('Eslovenia'),
('España'),
('Estados Unidos'),
('Estonia'),
('Esuatini'),
('Etiopía'),
('Filipinas'),
('Finlandia'),
('Fiyi'),
('Francia'),
('Gabón'),
('Gambia'),
('Georgia'),
('Ghana'),
('Granada'),
('Grecia'),
('Guatemala'),
('Guinea'),
('Guinea-Bisáu'),
('Guinea Ecuatorial'),
('Guyana'),
('Haití'),
('Honduras'),
('Hungría'),
('India'),
('Indonesia'),
('Irak'),
('Irán'),
('Irlanda'),
('Islandia'),
('Islas Marshall'),
('Islas Salomón'),
('Israel'),
('Italia'),
('Jamaica'),
('Japón'),
('Jordania'),
('Kazajistán'),
('Kenia'),
('Kirguistán'),
('Kiribati'),
('Kuwait'),
('Laos'),
('Lesoto'),
('Letonia'),
('Líbano'),
('Liberia'),
('Libia'),
('Liechtenstein'),
('Lituania'),
('Luxemburgo'),
('Macedonia del Norte'),
('Madagascar'),
('Malasia'),
('Malaui'),
('Maldivas'),
('Malí'),
('Malta'),
('Marruecos'),
('Mauricio'),
('Mauritania'),
('México'),
('Micronesia'),
('Moldavia'),
('Mónaco'),
('Mongolia'),
('Montenegro'),
('Mozambique'),
('Namibia'),
('Nauru'),
('Nepal'),
('Nicaragua'),
('Níger'),
('Nigeria'),
('Noruega'),
('Nueva Zelanda'),
('Omán'),
('Países Bajos'),
('Pakistán'),
('Palaos'),
('Panamá'),
('Papúa Nueva Guinea'),
('Paraguay'),
('Perú'),
('Polonia'),
('Portugal'),
('Reino Unido'),
('República Centroafricana'),
('República Checa'),
('República del Congo'),
('República Democrática del Congo'),
('República Dominicana'),
('Ruanda'),
('Rumanía'),
('Rusia'),
('Samoa'),
('San Cristóbal y Nieves'),
('San Marino'),
('San Vicente y las Granadinas'),
('Santa Lucía'),
('Santo Tomé y Príncipe'),
('Senegal'),
('Serbia'),
('Seychelles'),
('Sierra Leona'),
('Singapur'),
('Siria'),
('Somalia'),
('Sri Lanka'),
('Sudáfrica'),
('Sudán'),
('Sudán del Sur'),
('Suecia'),
('Suiza'),
('Surinam'),
('Tailandia'),
('Tanzania'),
('Tayikistán'),
('Timor Oriental'),
('Togo'),
('Tonga'),
('Trinidad y Tobago'),
('Túnez'),
('Turkmenistán'),
('Turquía'),
('Tuvalu'),
('Ucrania'),
('Uganda'),
('Uruguay'),
('Uzbekistán'),
('Vanuatu'),
('Vaticano'),
('Venezuela'),
('Vietnam'),
('Yemen'),
('Yibuti'),
('Zambia'),
('Zimbabue');



--insertar ciudades
INSERT INTO ciudad (nombre, id_pais) VALUES
('Madrid', (SELECT id FROM pais WHERE nombre = 'España')),
('Barcelona', (SELECT id FROM pais WHERE nombre = 'España')),
('Valencia', (SELECT id FROM pais WHERE nombre = 'España')),
('Sevilla', (SELECT id FROM pais WHERE nombre = 'España')),
('Zaragoza', (SELECT id FROM pais WHERE nombre = 'España')),
('Málaga', (SELECT id FROM pais WHERE nombre = 'España')),
('Murcia', (SELECT id FROM pais WHERE nombre = 'España')),
('Palma', (SELECT id FROM pais WHERE nombre = 'España')),
('Las Palmas de Gran Canaria', (SELECT id FROM pais WHERE nombre = 'España')),
('Bilbao', (SELECT id FROM pais WHERE nombre = 'España')),
('Alicante', (SELECT id FROM pais WHERE nombre = 'España')),
('Córdoba', (SELECT id FROM pais WHERE nombre = 'España')),
('Valladolid', (SELECT id FROM pais WHERE nombre = 'España')),
('Vigo', (SELECT id FROM pais WHERE nombre = 'España')),
('Gijón', (SELECT id FROM pais WHERE nombre = 'España')),
('L''Hospitalet de Llobregat', (SELECT id FROM pais WHERE nombre = 'España')),
('A Coruña', (SELECT id FROM pais WHERE nombre = 'España')),
('Vitoria', (SELECT id FROM pais WHERE nombre = 'España')),
('Granada', (SELECT id FROM pais WHERE nombre = 'España')),
('Elche', (SELECT id FROM pais WHERE nombre = 'España')),
('Oviedo', (SELECT id FROM pais WHERE nombre = 'España')),
('Badalona', (SELECT id FROM pais WHERE nombre = 'España')),
('Cartagena', (SELECT id FROM pais WHERE nombre = 'España')),
('Terrassa', (SELECT id FROM pais WHERE nombre = 'España')),
('Jerez de la Frontera', (SELECT id FROM pais WHERE nombre = 'España')),
('Sabadell', (SELECT id FROM pais WHERE nombre = 'España')),
('Móstoles', (SELECT id FROM pais WHERE nombre = 'España')),
('Santa Cruz de Tenerife', (SELECT id FROM pais WHERE nombre = 'España')),
('Pamplona', (SELECT id FROM pais WHERE nombre = 'España')),
('Almería', (SELECT id FROM pais WHERE nombre = 'España')),
('Alcalá de Henares', (SELECT id FROM pais WHERE nombre = 'España')),
('Fuenlabrada', (SELECT id FROM pais WHERE nombre = 'España')),
('Leganés', (SELECT id FROM pais WHERE nombre = 'España')),
('San Sebastián', (SELECT id FROM pais WHERE nombre = 'España')),
('Santander', (SELECT id FROM pais WHERE nombre = 'España')),
('Burgos', (SELECT id FROM pais WHERE nombre = 'España')),
('Castellón de la Plana', (SELECT id FROM pais WHERE nombre = 'España')),
('Albacete', (SELECT id FROM pais WHERE nombre = 'España')),
('Getafe', (SELECT id FROM pais WHERE nombre = 'España')),
('Salamanca', (SELECT id FROM pais WHERE nombre = 'España')),
('Huelva', (SELECT id FROM pais WHERE nombre = 'España')),
('Logroño', (SELECT id FROM pais WHERE nombre = 'España')),
('Badajoz', (SELECT id FROM pais WHERE nombre = 'España')),
('Tarragona', (SELECT id FROM pais WHERE nombre = 'España')),
('León', (SELECT id FROM pais WHERE nombre = 'España')),
('Cádiz', (SELECT id FROM pais WHERE nombre = 'España')),
('Lleida', (SELECT id FROM pais WHERE nombre = 'España')),
('Marbella', (SELECT id FROM pais WHERE nombre = 'España')),
('Jaén', (SELECT id FROM pais WHERE nombre = 'España')),
('Ourense', (SELECT id FROM pais WHERE nombre = 'España')),
('Santiago de Compostela', (SELECT id FROM pais WHERE nombre = 'España')),
('Girona', (SELECT id FROM pais WHERE nombre = 'España')),
('Lugo', (SELECT id FROM pais WHERE nombre = 'España')),
('Cáceres', (SELECT id FROM pais WHERE nombre = 'España')),
('Toledo', (SELECT id FROM pais WHERE nombre = 'España')),
('Melilla', (SELECT id FROM pais WHERE nombre = 'España')),
('Ceuta', (SELECT id FROM pais WHERE nombre = 'España')),
('Benidorm', (SELECT id FROM pais WHERE nombre = 'España')),
('Ibiza', (SELECT id FROM pais WHERE nombre = 'España')),
('Torremolinos', (SELECT id FROM pais WHERE nombre = 'España')),
('Fuengirola', (SELECT id FROM pais WHERE nombre = 'España')),
('Roquetas de Mar', (SELECT id FROM pais WHERE nombre = 'España')),
('Dos Hermanas', (SELECT id FROM pais WHERE nombre = 'España')),
('Estepona', (SELECT id FROM pais WHERE nombre = 'España')),
('Benalmádena', (SELECT id FROM pais WHERE nombre = 'España')),
('Pontevedra', (SELECT id FROM pais WHERE nombre = 'España')),
('Reus', (SELECT id FROM pais WHERE nombre = 'España')),
('Torrent', (SELECT id FROM pais WHERE nombre = 'España')),
('Avilés', (SELECT id FROM pais WHERE nombre = 'España')),
('Mérida', (SELECT id FROM pais WHERE nombre = 'España')),
('Segovia', (SELECT id FROM pais WHERE nombre = 'España')),
('Cuenca', (SELECT id FROM pais WHERE nombre = 'España')),
('Ávila', (SELECT id FROM pais WHERE nombre = 'España')),
('Zamora', (SELECT id FROM pais WHERE nombre = 'España')),
('Soria', (SELECT id FROM pais WHERE nombre = 'España')),
('Teruel', (SELECT id FROM pais WHERE nombre = 'España')),
('Huesca', (SELECT id FROM pais WHERE nombre = 'España')),
('Ciudad Real', (SELECT id FROM pais WHERE nombre = 'España')),
('Guadalajara', (SELECT id FROM pais WHERE nombre = 'España')),
('Talavera de la Reina', (SELECT id FROM pais WHERE nombre = 'España')),
('Manresa', (SELECT id FROM pais WHERE nombre = 'España')),
('Rubí', (SELECT id FROM pais WHERE nombre = 'España')),
('Vic', (SELECT id FROM pais WHERE nombre = 'España')),
('Blanes', (SELECT id FROM pais WHERE nombre = 'España')),
('Sitges', (SELECT id FROM pais WHERE nombre = 'España')),
('Lloret de Mar', (SELECT id FROM pais WHERE nombre = 'España')),
('Calella', (SELECT id FROM pais WHERE nombre = 'España')),
('Cambrils', (SELECT id FROM pais WHERE nombre = 'España')),
('Peñíscola', (SELECT id FROM pais WHERE nombre = 'España')),
('Denia', (SELECT id FROM pais WHERE nombre = 'España')),
('Jávea', (SELECT id FROM pais WHERE nombre = 'España')),
('Altea', (SELECT id FROM pais WHERE nombre = 'España')),
('Motril', (SELECT id FROM pais WHERE nombre = 'España')),
('Nerja', (SELECT id FROM pais WHERE nombre = 'España')),
('Ronda', (SELECT id FROM pais WHERE nombre = 'España')),
('Utrera', (SELECT id FROM pais WHERE nombre = 'España')),
('Linares', (SELECT id FROM pais WHERE nombre = 'España')),
('Andújar', (SELECT id FROM pais WHERE nombre = 'España')),
('Úbeda', (SELECT id FROM pais WHERE nombre = 'España')),
('Baeza', (SELECT id FROM pais WHERE nombre = 'España')),
('Arrecife', (SELECT id FROM pais WHERE nombre = 'España')),
('Puerto del Rosario', (SELECT id FROM pais WHERE nombre = 'España')),
('San Cristóbal de La Laguna', (SELECT id FROM pais WHERE nombre = 'España')),
('Adeje', (SELECT id FROM pais WHERE nombre = 'España')),
('Telde', (SELECT id FROM pais WHERE nombre = 'España')),
('Maspalomas', (SELECT id FROM pais WHERE nombre = 'España')),
('Ferrol', (SELECT id FROM pais WHERE nombre = 'España')),
('Narón', (SELECT id FROM pais WHERE nombre = 'España')),
('Vilanova i la Geltrú', (SELECT id FROM pais WHERE nombre = 'España')),
('Igualada', (SELECT id FROM pais WHERE nombre = 'España')),
('Mollet del Vallès', (SELECT id FROM pais WHERE nombre = 'España')),
('Hospitalet de l’Infant', (SELECT id FROM pais WHERE nombre = 'España')),
('Algeciras', (SELECT id FROM pais WHERE nombre = 'España')),
('San Fernando', (SELECT id FROM pais WHERE nombre = 'España')),
('Chiclana de la Frontera', (SELECT id FROM pais WHERE nombre = 'España')),
('El Puerto de Santa María', (SELECT id FROM pais WHERE nombre = 'España')),
('Orihuela', (SELECT id FROM pais WHERE nombre = 'España')),
('Elda', (SELECT id FROM pais WHERE nombre = 'España')),
('Villena', (SELECT id FROM pais WHERE nombre = 'España')),
('Yecla', (SELECT id FROM pais WHERE nombre = 'España')),
('Lorca', (SELECT id FROM pais WHERE nombre = 'España')),
('Molina de Segura', (SELECT id FROM pais WHERE nombre = 'España')),
('Cullera', (SELECT id FROM pais WHERE nombre = 'España')),
('Gandía', (SELECT id FROM pais WHERE nombre = 'España')),
('Sagunto', (SELECT id FROM pais WHERE nombre = 'España')),
('Xàtiva', (SELECT id FROM pais WHERE nombre = 'España')),
('Ontinyent', (SELECT id FROM pais WHERE nombre = 'España')),
('Tomelloso', (SELECT id FROM pais WHERE nombre = 'España')),
('Puertollano', (SELECT id FROM pais WHERE nombre = 'España')),
('Alcázar de San Juan', (SELECT id FROM pais WHERE nombre = 'España')),
('Don Benito', (SELECT id FROM pais WHERE nombre = 'España')),
('Plasencia', (SELECT id FROM pais WHERE nombre = 'España')),
('Villanueva de la Serena', (SELECT id FROM pais WHERE nombre = 'España')),
('Monzón', (SELECT id FROM pais WHERE nombre = 'España')),
('Barbastro', (SELECT id FROM pais WHERE nombre = 'España')),
('Calatayud', (SELECT id FROM pais WHERE nombre = 'España')),
('Eibar', (SELECT id FROM pais WHERE nombre = 'España')),
('Irún', (SELECT id FROM pais WHERE nombre = 'España')),
('Errenteria', (SELECT id FROM pais WHERE nombre = 'España')),
('París', (SELECT id FROM pais WHERE nombre = 'Francia')),
('Londres', (SELECT id FROM pais WHERE nombre = 'Reino Unido')),
('Roma', (SELECT id FROM pais WHERE nombre = 'Italia')),
('Berlín', (SELECT id FROM pais WHERE nombre = 'Alemania')),
('Lisboa', (SELECT id FROM pais WHERE nombre = 'Portugal')),
('Ámsterdam', (SELECT id FROM pais WHERE nombre = 'Países Bajos')),
('Bruselas', (SELECT id FROM pais WHERE nombre = 'Bélgica')),
('Viena', (SELECT id FROM pais WHERE nombre = 'Austria')),
('Praga', (SELECT id FROM pais WHERE nombre = 'República Checa')),
('Dublín', (SELECT id FROM pais WHERE nombre = 'Irlanda'));



--insertar ciudad extra
INSERT INTO ciudad (id_ciudad, nombre, id_pais)
VALUES (150, 'Otra ciudad / extranjero', NULL);

--insertar usuario con cuenta eliminada
INSERT INTO usuarios (
    nombre_usuario,
    nombre,
    email,
    contrasenya,
    fecha_nacimiento,
    bio,
    genero,
    fecha_registro,
    activo,
    foto_perfil,
    id_ciudad
)
VALUES (
    'deleted_account',
    'Usuario eliminado',
    'deleted@matchup.com',
    'NO_LOGIN',
    '2000-01-01',
    '',
    'OTRO',
    NOW(),
    true,
    NULL,
    1
);